      SUBROUTINE RANSET
      INCLUDE 'ising.inc'
C
      IF (ISEED .LE. 0) ISEED=12345678
C
      RETURN
      END
C
      REAL FUNCTION RANF()
      INCLUDE 'ising.inc'
C
      INTEGER IA, IC, IM
      PARAMETER (IA=1103515245)
      PARAMETER (IM=2147483647)
      PARAMETER (IC = 12345)
C
      ISEED = ISEED*IA+IC
C
      IF (ISEED .LT. 0) ISEED = ISEED + IM
C
      RANF=REAL(ISEED)/REAL(IM)
C
      RETURN
      END
