      SUBROUTINE HDF5_INIT(L, NSTEPS)
      INTEGER L, NSTEPS
      RETURN
      END
C
      SUBROUTINE SNAPSHOT_HDF5(STEP, L, SPIN)
      INTEGER STEP, L
      INTEGER SPIN(L,L)
      CALL SNAPSHOT_HDF5_(STEP, L, SPIN)
      RETURN
      END
C
      SUBROUTINE HDF5_CLOSE()
      CALL HDF5_CLOSE_()
      RETURN
      END
